# for h2 database config, I haven't added the username or password yet. Leaving it as default

spring.application.name=dispatch-service
spring.datasource.url=jdbc:h2:mem:dispatch_service
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081